# Generated by Django 3.2.14 on 2022-07-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_date_date_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_title', models.CharField(max_length=100)),
                ('calendar_final', models.DateField()),
                ('calendar_created', models.DateTimeField(auto_now_add=True)),
                ('calendar_damdang', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
